<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="67053" started-at="2019-03-09T11:09:41Z" finished-at="2019-03-09T11:10:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="67053" started-at="2019-03-09T11:09:41Z" finished-at="2019-03-09T11:10:48Z">
      <class name="com.training.sanity.tests.HTestsRETC_81_1">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.HTestsRETC_81_1@39aeed2f]" name="setUpBeforeClass" is-config="true" duration-ms="10" started-at="2019-03-09T16:39:41Z" finished-at="2019-03-09T16:39:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.HTestsRETC_81_1@39aeed2f]" name="setUp" is-config="true" duration-ms="47614" started-at="2019-03-09T16:39:41Z" finished-at="2019-03-09T16:40:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginDBTest(java.lang.String, java.lang.String)[pri:1, instance:com.training.sanity.tests.HTestsRETC_81_1@39aeed2f]" name="loginDBTest" duration-ms="13126" started-at="2019-03-09T16:40:29Z" data-provider="excel-inputs-login" finished-at="2019-03-09T16:40:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDBTest -->
        <test-method status="FAIL" signature="validFeatureCreation(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.training.sanity.tests.HTestsRETC_81_1@39aeed2f]" name="validFeatureCreation" duration-ms="3014" started-at="2019-03-09T16:40:43Z" data-provider="db-feature" finished-at="2019-03-09T16:40:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[New Launches]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[launch]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Apartments]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[New Launches of vilas, apartments, flats]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [launch1] but found [launch]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [launch1] but found [launch]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.training.sanity.tests.HTestsRETC_81_1.validFeatureCreation(HTestsRETC_81_1.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validFeatureCreation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.HTestsRETC_81_1@39aeed2f]" name="tearDown" is-config="true" duration-ms="2001" started-at="2019-03-09T16:40:46Z" finished-at="2019-03-09T16:40:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.HTestsRETC_81_1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
